const SocketEvent = {
    USER_SERVERS: 'userServers',
    CREATE_SERVER: 'createServer',
    JOIN_SERVER: 'joinServer',
    CREATE_CHANNEL: 'createChannel',
    MESSAGE_SERVER: 'messageServer',
    LEAVE_SERVER: 'leaveServer',
    DELETE_SERVER: 'deleteServer',
    DISCONNECT: 'disconnect',
    USER_SERVERS_SUCCESS: 'userServersSuccess',
    USER_SERVERS_ERROR: 'userServersError',
    CREATE_SERVER_SUCCESS: 'createServerSuccess',
    CREATE_SERVER_ERROR: 'createServerError',
    JOIN_SERVER_SUCCESS: 'joinServerSuccess',
    JOIN_SERVER_ERROR: 'joinServerError',
    MEMBER_JOINED: 'memberJoined',
    CREATE_CHANNEL_SUCCESS: 'createChannelSuccess',
    CREATE_CHANNEL_ERROR: 'createChannelError',
    MESSAGE_SERVER_SUCCESS: 'messageServerSuccess',
    MESSAGE_SERVER_ERROR: 'messageServerError',
    LEAVE_SERVER_SUCCESS: 'leaveServerSuccess',
    LEAVE_SERVER_ERROR: 'leaveServerError',
    DELETE_SERVER_SUCCESS: 'deleteServerSuccess',
    DELETE_SERVER_ERROR: 'deleteServerError',
} as const

export { SocketEvent }
